### ISSUE TITLE
Learn -> Governance -> Roadmap

### ISSUE THREAD

**Issue by wilwade** [LibertyDSNP/frequency-docs#24]
## Outline
- [ ] Where are we right now?
- [ ] The Phases of Governance
    - [ ] Launch (Sudo + Internal Councils)
    - [ ] Removal of Sudo
    - [ ] Launch Councils (External Councils)
    - [ ] Token Voting (aka Frequency Democracy 1.0)
    - [ ] Frequency Democracy 2.0

## Sources
- Notion "Frequency Governance and Decentralization Ideation"
- Concept Posts
